[package]
name = "nato"
version = "0.1.0"
edition = "2021"
authors = ["Wouter de Bie"]
description = "Small tool to help you spell in the NATO alphabet"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
