[package]
name = "nato"
version = "0.1.1"
edition = "2021"
authors = ["Wouter de Bie"]
description = "Small tool to help you spell in phonetic alphabets"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.6", features = ['derive'] }
indexmap = "1.8.0"
rust-embed="6.3.0"
substring = "1.4.5"
tabular = "0.2.0"
